name: Sync Live Source

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run python script
        run: python script/get_live.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global safe.directory "$GITHUB_WORKSPACE"
          git add -A
          git status
          git commit -m "auto update live.m3u" || echo ">>> nothing changed"
          git push origin main
